In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, recall_score, precision_score, roc_auc_score, confusion_matrix, classification_report
from sklearn import metrics
import matplotlib.pyplot as plt

# Loading Dataset

In [ ]:
df = pd.read_csv('D3_Heart_Dataset.csv')
df.head()

Age Gender ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0   40      M           ATA        140          289          0     Normal   
1   49      F           NAP        160          180          0     Normal   
2   37      M           ATA        130          283          0         ST   
3   48      F           ASY        138          214          0     Normal   
4   54      M           NAP        150          195          0     Normal   

   MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0    172              N      0.0       Up             0  
1    156              N      1.0     Flat             1  
2     98              N      0.0       Up             0  
3    108              Y      1.5     Flat             1  
4    122              N      0.0       Up             0

# Separating Features

In [ ]:
df = df[df['Oldpeak'] >=0]
df

Age Gender ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40      M           ATA        140          289          0     Normal   
1     49      F           NAP        160          180          0     Normal   
2     37      M           ATA        130          283          0         ST   
3     48      F           ASY        138          214          0     Normal   
4     54      M           NAP        150          195          0     Normal   
..   ...    ...           ...        ...          ...        ...        ...   
913   45      M            TA        110          264          0     Normal   
914   68      M           ASY        144          193          1     Normal   
915   57      M           ASY        130          131          0     Normal   
916   57      F           ATA        130          236          0        LVH   
917   38      M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[905 rows x 12 columns]

In [ ]:
X = df.drop("HeartDisease",axis=1)

In [ ]:
X

Age Gender ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40      M           ATA        140          289          0     Normal   
1     49      F           NAP        160          180          0     Normal   
2     37      M           ATA        130          283          0         ST   
3     48      F           ASY        138          214          0     Normal   
4     54      M           NAP        150          195          0     Normal   
..   ...    ...           ...        ...          ...        ...        ...   
913   45      M            TA        110          264          0     Normal   
914   68      M           ASY        144          193          1     Normal   
915   57      M           ASY        130          131          0     Normal   
916   57      F           ATA        130          236          0        LVH   
917   38      M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  
0      172              N      0.0       Up  
1      156              N      1.0     Flat  
2       98              N      0.0       Up  
3      108              Y      1.5     Flat  
4      122              N      0.0       Up  
..     ...            ...      ...      ...  
913    132              N      1.2     Flat  
914    141              N      3.4     Flat  
915    115              Y      1.2     Flat  
916    174              N      0.0     Flat  
917    173              N      0.0       Up  

[905 rows x 11 columns]

In [ ]:
Y = df["HeartDisease"]
Y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 905, dtype: int64

# Apply Ordinal Encoding

In [ ]:
X['Gender'].unique()

array(['M', 'F'], dtype=object)

In [ ]:
X['Gender'] = X['Gender'].replace('M',1)
X['Gender'] = X['Gender'].replace('F',2)
X

<ipython-input-66-442b5a1ffada>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X['Gender'] = X['Gender'].replace('F',2)


Age  Gender ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40       1           ATA        140          289          0     Normal   
1     49       2           NAP        160          180          0     Normal   
2     37       1           ATA        130          283          0         ST   
3     48       2           ASY        138          214          0     Normal   
4     54       1           NAP        150          195          0     Normal   
..   ...     ...           ...        ...          ...        ...        ...   
913   45       1            TA        110          264          0     Normal   
914   68       1           ASY        144          193          1     Normal   
915   57       1           ASY        130          131          0     Normal   
916   57       2           ATA        130          236          0        LVH   
917   38       1           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  
0      172              N      0.0       Up  
1      156              N      1.0     Flat  
2       98              N      0.0       Up  
3      108              Y      1.5     Flat  
4      122              N      0.0       Up  
..     ...            ...      ...      ...  
913    132              N      1.2     Flat  
914    141              N      3.4     Flat  
915    115              Y      1.2     Flat  
916    174              N      0.0     Flat  
917    173              N      0.0       Up  

[905 rows x 11 columns]

In [ ]:
X['ChestPainType'].unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [ ]:
X['ChestPainType'] = X['ChestPainType'].replace("ATA",1)
X['ChestPainType'] = X['ChestPainType'].replace("NAP",2)
X['ChestPainType'] = X['ChestPainType'].replace("ASY",3)
X['ChestPainType'] = X['ChestPainType'].replace("TA",4)
X

<ipython-input-68-a84c06e94de6>:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X['ChestPainType'] = X['ChestPainType'].replace("TA",4)


Age  Gender  ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40       1              1        140          289          0     Normal   
1     49       2              2        160          180          0     Normal   
2     37       1              1        130          283          0         ST   
3     48       2              3        138          214          0     Normal   
4     54       1              2        150          195          0     Normal   
..   ...     ...            ...        ...          ...        ...        ...   
913   45       1              4        110          264          0     Normal   
914   68       1              3        144          193          1     Normal   
915   57       1              3        130          131          0     Normal   
916   57       2              1        130          236          0        LVH   
917   38       1              2        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  
0      172              N      0.0       Up  
1      156              N      1.0     Flat  
2       98              N      0.0       Up  
3      108              Y      1.5     Flat  
4      122              N      0.0       Up  
..     ...            ...      ...      ...  
913    132              N      1.2     Flat  
914    141              N      3.4     Flat  
915    115              Y      1.2     Flat  
916    174              N      0.0     Flat  
917    173              N      0.0       Up  

[905 rows x 11 columns]

In [ ]:
X['RestingECG'].unique()

array(['Normal', 'ST', 'LVH'], dtype=object)

In [ ]:
X['RestingECG'] = X['RestingECG'].replace('Normal',1)
X['RestingECG'] = X['RestingECG'].replace('ST',2)
X['RestingECG'] = X['RestingECG'].replace('LVH',3)
X

<ipython-input-70-3e5afec19488>:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X['RestingECG'] = X['RestingECG'].replace('LVH',3)


Age  Gender  ChestPainType  RestingBP  Cholesterol  FastingBS  \
0     40       1              1        140          289          0   
1     49       2              2        160          180          0   
2     37       1              1        130          283          0   
3     48       2              3        138          214          0   
4     54       1              2        150          195          0   
..   ...     ...            ...        ...          ...        ...   
913   45       1              4        110          264          0   
914   68       1              3        144          193          1   
915   57       1              3        130          131          0   
916   57       2              1        130          236          0   
917   38       1              2        138          175          0   

     RestingECG  MaxHR ExerciseAngina  Oldpeak ST_Slope  
0             1    172              N      0.0       Up  
1             1    156              N      1.0     Flat  
2             2     98              N      0.0       Up  
3             1    108              Y      1.5     Flat  
4             1    122              N      0.0       Up  
..          ...    ...            ...      ...      ...  
913           1    132              N      1.2     Flat  
914           1    141              N      3.4     Flat  
915           1    115              Y      1.2     Flat  
916           3    174              N      0.0     Flat  
917           1    173              N      0.0       Up  

[905 rows x 11 columns]

In [ ]:
X['ExerciseAngina'].unique()

array(['N', 'Y'], dtype=object)

In [ ]:
X['ExerciseAngina'] = X['ExerciseAngina'].replace('N',1)
X['ExerciseAngina'] = X['ExerciseAngina'].replace('Y',2)
X

<ipython-input-72-3ff2d30b393d>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X['ExerciseAngina'] = X['ExerciseAngina'].replace('Y',2)


Age  Gender  ChestPainType  RestingBP  Cholesterol  FastingBS  \
0     40       1              1        140          289          0   
1     49       2              2        160          180          0   
2     37       1              1        130          283          0   
3     48       2              3        138          214          0   
4     54       1              2        150          195          0   
..   ...     ...            ...        ...          ...        ...   
913   45       1              4        110          264          0   
914   68       1              3        144          193          1   
915   57       1              3        130          131          0   
916   57       2              1        130          236          0   
917   38       1              2        138          175          0   

     RestingECG  MaxHR  ExerciseAngina  Oldpeak ST_Slope  
0             1    172               1      0.0       Up  
1             1    156               1      1.0     Flat  
2             2     98               1      0.0       Up  
3             1    108               2      1.5     Flat  
4             1    122               1      0.0       Up  
..          ...    ...             ...      ...      ...  
913           1    132               1      1.2     Flat  
914           1    141               1      3.4     Flat  
915           1    115               2      1.2     Flat  
916           3    174               1      0.0     Flat  
917           1    173               1      0.0       Up  

[905 rows x 11 columns]

In [ ]:
X['ST_Slope'].unique()

array(['Up', 'Flat', 'Down'], dtype=object)

In [ ]:
X['ST_Slope'] = X['ST_Slope'].replace('Up',1)
X['ST_Slope'] = X['ST_Slope'].replace('Flat',2)
X['ST_Slope'] = X['ST_Slope'].replace('Down',3)
X

<ipython-input-74-f8455a08fba7>:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X['ST_Slope'] = X['ST_Slope'].replace('Down',3)


Age  Gender  ChestPainType  RestingBP  Cholesterol  FastingBS  \
0     40       1              1        140          289          0   
1     49       2              2        160          180          0   
2     37       1              1        130          283          0   
3     48       2              3        138          214          0   
4     54       1              2        150          195          0   
..   ...     ...            ...        ...          ...        ...   
913   45       1              4        110          264          0   
914   68       1              3        144          193          1   
915   57       1              3        130          131          0   
916   57       2              1        130          236          0   
917   38       1              2        138          175          0   

     RestingECG  MaxHR  ExerciseAngina  Oldpeak  ST_Slope  
0             1    172               1      0.0         1  
1             1    156               1      1.0         2  
2             2     98               1      0.0         1  
3             1    108               2      1.5         2  
4             1    122               1      0.0         1  
..          ...    ...             ...      ...       ...  
913           1    132               1      1.2         2  
914           1    141               1      3.4         2  
915           1    115               2      1.2         2  
916           3    174               1      0.0         2  
917           1    173               1      0.0         1  

[905 rows x 11 columns]

# Splitting data into Training and Testing

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.20,random_state=0)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(724, 11)
(181, 11)
(724,)
(181,)


# 2. Analyze the performance of naïve Bayes with respect to accuracy, recall, precision, FPR, and ROC metrics obtained for heart dataset.

## Creating Gaussian Naive Bayes

In [ ]:
classifier1 = GaussianNB()
model1 = classifier1.fit(X_train,Y_train)

In [ ]:
y_pred1 = model1.predict(X_test)

In [ ]:
print('The accuracy is '+str(accuracy_score(Y_test,y_pred1)*100)+"%")

The accuracy is 83.15217391304348%


In [ ]:
print(confusion_matrix(Y_test, y_pred1))
target_names = ['class 0', 'class 1']
print(classification_report(Y_test, y_pred1, target_names=target_names))
fpr, tpr, thresholds = metrics.roc_curve(Y_test, y_pred1, pos_label=1)
roc_auc = metrics.auc(fpr, tpr)
print("Area under the ROC curve : %f" % roc_auc)


[[60 17]
 [14 93]]
              precision    recall  f1-score   support

     class 0       0.81      0.78      0.79        77
     class 1       0.85      0.87      0.86       107

    accuracy                           0.83       184
   macro avg       0.83      0.82      0.83       184
weighted avg       0.83      0.83      0.83       184

Area under the ROC curve : 0.824190


# 3. Test the naïve Bayes algorithm with prior probabilities (0.25, 0.75), (0.75, 0.25), and (0.5, 0.5) on heart dataset. Study the impact on performance metrics.

## Creating Naive Bayes on Prior Probabilities

### prior probability (0.25,0.75)

In [ ]:
classifier2 = GaussianNB(priors=[0.25,0.75])
model2 = classifier2.fit(X_train,Y_train)
y_pred2 = model2.predict(X_test)

In [ ]:
print('the accuracy is '+str(accuracy_score(Y_test,y_pred2)*100)+"%")
print(confusion_matrix(Y_test, y_pred2))
target_names = ['class 0', 'class 1']
print(classification_report(Y_test, y_pred2, target_names=target_names))

the accuracy is 84.23913043478261%
[[58 19]
 [10 97]]
              precision    recall  f1-score   support

     class 0       0.85      0.75      0.80        77
     class 1       0.84      0.91      0.87       107

    accuracy                           0.84       184
   macro avg       0.84      0.83      0.83       184
weighted avg       0.84      0.84      0.84       184



### prior probability (0.75,0.25)

In [ ]:
classifier3 = GaussianNB(priors=[0.75,0.25])
model3 = classifier3.fit(X_train,Y_train)
y_pred3 = model3.predict(X_test)

In [ ]:
print('the accuracy is '+str(accuracy_score(Y_test,y_pred3)*100)+"%")
print(confusion_matrix(Y_test, y_pred3))
target_names = ['class 0', 'class 1']
print(classification_report(Y_test, y_pred3, target_names=target_names))

the accuracy is 83.69565217391305%
[[63 14]
 [16 91]]
              precision    recall  f1-score   support

     class 0       0.80      0.82      0.81        77
     class 1       0.87      0.85      0.86       107

    accuracy                           0.84       184
   macro avg       0.83      0.83      0.83       184
weighted avg       0.84      0.84      0.84       184



### prior probability (0.5, 0.5)

In [ ]:
classifier4 = GaussianNB(priors=[0.5,0.5])
model4 = classifier4.fit(X_train,Y_train)
y_pred4 = model4.predict(X_test)

In [ ]:
print('the accuracy is '+str(accuracy_score(Y_test,y_pred4)*100)+"%")
print(confusion_matrix(Y_test, y_pred4))
target_names = ['class 0', 'class 1']
print(classification_report(Y_test, y_pred4, target_names=target_names))

the accuracy is 83.69565217391305%
[[61 16]
 [14 93]]
              precision    recall  f1-score   support

     class 0       0.81      0.79      0.80        77
     class 1       0.85      0.87      0.86       107

    accuracy                           0.84       184
   macro avg       0.83      0.83      0.83       184
weighted avg       0.84      0.84      0.84       184



# 4. Compare the Guassian implementation of naïve Bayes algorithm with Bernoulli and Multinomial on heart dataset. Study the impact on performance metrics.


## Creating Multinomial Naive Bayes

In [ ]:
from sklearn.naive_bayes import MultinomialNB

# Creating Multinomial Naive Bayes Object
multinomialClassifer = MultinomialNB()

# Training the model
multinomialModel = multinomialClassifer.fit(X_train, Y_train)

# Evaluating the model
Y_pred3 = multinomialModel.predict(X_test)
print("The accuracy is "+str(metrics.accuracy_score(Y_test,Y_pred3)*100)+"%")
print(confusion_matrix(Y_test, Y_pred3))

The accuracy is 69.61325966850829%
[[64 12]
 [43 62]]


## Creating Bernoulli Naive Bayes

In [ ]:
from sklearn.naive_bayes import BernoulliNB

bernoulliClassifier = BernoulliNB()
bernoulliModel = bernoulliClassifier.fit(X_train, Y_train)
Y_pred4 = bernoulliModel.predict(X_test)
print("The accuracy is "+str(metrics.accuracy_score(Y_test,Y_pred4)*100)+"%")
print(confusion_matrix(Y_test, Y_pred4))

The accuracy is 79.00552486187846%
[[46 30]
 [ 8 97]]


# 5. Test the naïve Bayes implementation with spambase dataset. Compare the spambase performance with the heart using the discussed metrics.

In [ ]:
spamdf = pd.read_csv('spambase.csv')
spamdf.head()

word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
0            0.00               0.64           0.64           0.0   
1            0.21               0.28           0.50           0.0   
2            0.06               0.00           0.71           0.0   
3            0.00               0.00           0.00           0.0   
4            0.00               0.00           0.00           0.0   

   word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
0           0.32            0.00              0.00                0.00   
1           0.14            0.28              0.21                0.07   
2           1.23            0.19              0.19                0.12   
3           0.63            0.00              0.31                0.63   
4           0.63            0.00              0.31                0.63   

   word_freq_order  word_freq_mail  ...  char_freq_;  char_freq_(  \
0             0.00            0.00  ...         0.00        0.000   
1             0.00            0.94  ...         0.00        0.132   
2             0.64            0.25  ...         0.01        0.143   
3             0.31            0.63  ...         0.00        0.137   
4             0.31            0.63  ...         0.00        0.135   

   char_freq_[  char_freq_!  char_freq_$  char_freq_#  \
0          0.0        0.778        0.000        0.000   
1          0.0        0.372        0.180        0.048   
2          0.0        0.276        0.184        0.010   
3          0.0        0.137        0.000        0.000   
4          0.0        0.135        0.000        0.000   

   capital_run_length_average  capital_run_length_longest  \
0                       3.756                          61   
1                       5.114                         101   
2                       9.821                         485   
3                       3.537                          40   
4                       3.537                          40   

   capital_run_length_total  spam  
0                       278     1  
1                      1028     1  
2                      2259     1  
3                       191     1  
4                       191     1  

[5 rows x 58 columns]

In [ ]:
X = spamdf.drop('spam',axis=1)
Y = spamdf['spam']

x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.20,random_state=0)
print(x_train.shape)
print(x_test.shape)

(3680, 57)
(921, 57)


In [ ]:
spam_model = GaussianNB()
spam_model.fit(x_train,y_train)
spam_pred = spam_model.predict(x_test)

In [ ]:
print('The accuracy is '+str(accuracy_score(y_test,spam_pred)*100)+"%")
print("The recall score is", recall_score(y_test, spam_pred)*100, "%")
print("The precision is", precision_score(y_test, spam_pred)*100, "%")
print("The roc score is", roc_auc_score(y_test, spam_pred)*100, "%")
print(confusion_matrix(y_test, spam_pred))
target_names = ['class 0', 'class 1']
print(classification_report(y_test, spam_pred, target_names=target_names))


The accuracy is 80.67318132464713%
The recall score is 93.21148825065274 %
The precision is 70.13752455795678 %
The roc score is 82.47935007328175 %
[[386 152]
 [ 26 357]]
              precision    recall  f1-score   support

     class 0       0.94      0.72      0.81       538
     class 1       0.70      0.93      0.80       383

    accuracy                           0.81       921
   macro avg       0.82      0.82      0.81       921
weighted avg       0.84      0.81      0.81       921

