# Machine Learning Lab 1



In [ ]:
import numpy as np

## 2. Create an ndarray using the following data. Write the code and outputs.


In [ ]:
data1 = np.array([1, 3, 9, 12, 18])
data2 = np.array([[1,5,2,0],[3,6,4,7]])
data3 = np.array([['7','6'],['5','4'],['3','2']])
data4 = np.array([[11,52,20,50],[34,61,43,17]])


In [ ]:
print('data1')
print(data1)
print("data2")
print(data2)
print("data3")
print(data3)
print("data4")
print(data4)

data1
[ 1  3  9 12 18]
data2
[[1 5 2 0]
 [3 6 4 7]]
data3
[['7' '6']
 ['5' '4']
 ['3' '2']]
data4
[[11 52 20 50]
 [34 61 43 17]]


## 3. Add Data1 in Data1. Multiply Data1 by 10. Convert Data1, Data2, Data3, and Data4 datatypes to integer.

In [ ]:
addData1 = data1+data1
mulData1 = data1*10

In [ ]:
print('Adding Data1 in Data1 = ',addData1)
print('Multiply Data1 by 10 = ',mulData1)

Adding Data1 in Data1 =  [ 2  6 18 24 36]
Multiply Data1 by 10 =  [ 10  30  90 120 180]


In [ ]:
ConvertedData1 = data1.astype(np.int32)
ConvertedData2 = data2.astype(np.int32)
ConvertedData3 = data3.astype(np.int32)
ConvertedData4 = data4.astype(np.int32)

In [ ]:
print(ConvertedData1.dtype)
print(ConvertedData2.dtype)
print(ConvertedData3.dtype)
print(ConvertedData4.dtype)

int32
int32
int32
int32


## 4. Create a 3x5 array of 0s. 2x8 array of 1s, 6x3 array of integer random numbers

In [ ]:
from numpy import random

In [ ]:
array0s = np.full((3, 5), 0)
array0s

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
array1s = np.full((2, 8), 1)
array1s

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
arrayRandomNumbers = random.randint(100,size=(6,3))
arrayRandomNumbers

array([[46,  0, 64],
       [57, 45, 43],
       [94, 26, 95],
       [28, 39, 95],
       [81, 70, 14],
       [66, 97, 27]])

## 5. Square the bold elements of Data1 and Data2. Hint: use indexing and slicing.

In [ ]:
newData1 = data1.copy()
newData1[2:4] = newData1[2:4] **2
newData1

array([  1,   3,  81, 144,  18])

In [ ]:
newData2 = data2.copy()
newData2[0,1] = newData2[0,1] **2
newData2[1,2] = newData2[1,2] **2
newData2


array([[ 1, 25,  2,  0],
       [ 3,  6, 16,  7]])

## 6. Consider an array Subjects = [[𝑀𝐿 𝑂𝑆 𝐶𝐶𝑁],[ 𝑂𝑆 𝐴𝐼 𝑀𝑃], [𝐶𝐶𝑁 𝑀𝐿 𝐴𝐼]] Set all courses to 0 except ML and AI. Hint: use Boolean indexing.

In [ ]:
Subjects = np.array([["ML","OS","CCN"],["OS","AI","MP"],["CCN","ML","AI"]])
# numpy built-in method
# newSubjects = np.isin(Subjects,["ML","AI"],invert=True)
# Subjects[newSubjects] = 0
# Subjects
# Boolean Indexing Method
Subjects[(Subjects != "ML") & (Subjects != "AI")] = 0
Subjects

array([['ML', '0', '0'],
       ['0', 'AI', '0'],
       ['0', 'ML', 'AI']], dtype='<U3')

## 7. Transpose the Data2, Data3, and Data4 arrays using appropriate function.


In [ ]:
transposeData1 = data1.copy()
transposeData2 = data2.copy()
transposeData3 = data3.copy()
transposeData4 = data4.copy()
transposeData1 = np.array([transposeData1]).T
transposeData2 = transposeData2.T
transposeData3 = transposeData3.T
transposeData4 = transposeData4.T
print("Transpose Data1")
print(transposeData1)
print("Transpose Data2")
print(transposeData2)
print("Transpose Data3")
print(transposeData3)
print("Transpose Data4")
print(transposeData4)


Transpose Data1
[[ 1]
 [ 3]
 [ 9]
 [12]
 [18]]
Transpose Data2
[[1 3]
 [5 6]
 [2 4]
 [0 7]]
Transpose Data3
[['7' '5' '3']
 ['6' '4' '2']]
Transpose Data4
[[11 34]
 [52 61]
 [20 43]
 [50 17]]


## 8. Concatenate Data2 and Data4 using vstack and hstack.


In [ ]:
# Using Vstack
concat = np.vstack((data2,data4))
concat

array([[ 1,  5,  2,  0],
       [ 3,  6,  4,  7],
       [11, 52, 20, 50],
       [34, 61, 43, 17]])

In [ ]:
# Using hstack
concat = np.hstack((data2,data4))
concat

array([[ 1,  5,  2,  0, 11, 52, 20, 50],
       [ 3,  6,  4,  7, 34, 61, 43, 17]])

## 9. Demean each column of Data2. Hint: use broadcasting.


In [ ]:
meanData2 = data2.mean(0)
demeanData2 = data2 - meanData2
demeanData2

array([[-1. , -0.5, -1. , -3.5],
       [ 1. ,  0.5,  1. ,  3.5]])

## 10. Convert Data2 shape into 4x2. Hint: Use reshape function.

In [ ]:
newShapeData2 = data2.reshape(4,2)
newShapeData2

array([[1, 5],
       [2, 0],
       [3, 6],
       [4, 7]])

## 11. Consider the table having marks of three students scored in three subjects. Compute the maximum score of each subject. Hint: use max function

In [ ]:
subjectMarks = np.array([[60,70,50],[40,60,80],[70,55,65]])
print("Subject1 max Score",subjectMarks[0].max())
print("Subject2 max Score",subjectMarks[1].max())
print("Subject3 max Score",subjectMarks[2].max())

Subject1 max Score 70
Subject2 max Score 80
Subject3 max Score 70


## 12. Compute the CGPA of all three students using the following formula and tables 1.11 and 1.12 (Hint:Use ufunc methods).


In [ ]:
creditHours = np.array([2, 3, 4])
totalCreditHours = sum(creditHours)
def marks_to_grade_point(marks):
    if marks >= 85:
        return 4.0
    elif 80<=marks<= 84:
        return 3.7
    elif 75<=marks<= 79:
        return 3.4
    elif 70<=marks<= 74:
        return 3.0
    elif 67<=marks<= 69:
        return 2.7
    elif 64<=marks<= 66:
        return 2.4
    elif 60<=marks<= 63:
        return 2.0
    elif 57<=marks<= 59:
        return 1.7
    elif 54<=marks<= 56:
        return 1.4
    elif 50<=marks<= 53:
        return 1.0
    elif marks<50:
        return 0.0
CGPA = []
for student_id in range(subjectMarks.shape[1]):  # Loop through each student
    total_weighted_points = 0  # Initialize weighted points for the student
    for subjectID in range(subjectMarks.shape[0]):  # Loop through each subject
        marks = subjectMarks[subjectID][student_id]  # Marks for the student in this subject
        gradePoint = marks_to_grade_point(marks)  # Convert marks to grade points
        total_weighted_points += gradePoint * creditHours[subjectID]  # Add weighted points
    # Calculating CGPA for the student
    studentcgpa = total_weighted_points / totalCreditHours
    CGPA.append(studentcgpa)

# Print the CGPA for each student
for i, studentcgpa in enumerate(CGPA, start=1):
    print(f"CGPA of Student {i}: {studentcgpa:.2f}")

CGPA of Student 1: 1.78
CGPA of Student 2: 1.96
CGPA of Student 3: 2.52


## 13. Compute the sorted unique values in subjects array.

In [ ]:
Subjects = np.array([["ML","OS","CCN"],["OS","AI","MP"],["CCN","ML","AI"]])
uniqueSubjects = np.unique(Subjects)
uniqueSubjects

array(['AI', 'CCN', 'ML', 'MP', 'OS'], dtype='<U3')

## 14. Compute the dot product and inverse of 4x4 random matrix. Hint: Use numpy.linalg functions.

In [ ]:
from numpy import random
a = random.randn(4,4)
dotProduct = a.dot(a)
dotProduct

array([[ 5.21983991,  1.2349607 ,  4.93834596, -1.11768244],
       [-1.25520297, -0.72885987, -0.97437805, -0.06896518],
       [-1.09922793, -0.26402026, -0.18250798,  1.22927714],
       [-1.74729678, -0.12939922,  0.02347213,  0.89898791]])

In [ ]:
from numpy.linalg import inv
inverse = inv(a)
inverse

array([[ 0.21832881, -0.63247349, -0.1475671 , -0.20209122],
       [ 0.00309059, -0.03755285, -1.33926736,  1.17565107],
       [ 0.25254641,  0.66005431,  0.85450922, -0.05643497],
       [-0.05209667, -0.79086265,  0.07068451,  0.60999947]])

## 15. Store all the created arrays on disk.


In [ ]:
np.savez('createdarrays.npz', data1=data1, data2=data2, data3=data3, data4=data4,subjects=Subjects,marks=subjectMarks)

In [ ]:
arch = np.load('createdarrays.npz')
print(arch['data1'])


[ 1  3  9 12 18]
